// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jQuery(function() {
    var AboutView, BrandingView, EditorialView, FontView, IllustrationView, ServiceView, VideoView, WebView, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;
    IllustrationView = (function(_super) {
      __extends(IllustrationView, _super);

      function IllustrationView() {
        _ref = IllustrationView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      IllustrationView.prototype.el = $('body');

      IllustrationView.prototype.events = {
        'click #btn-illustration': 'showIllustration'
      };

      IllustrationView.prototype.pages = {
        illustration: _.template($('#illustration').html())
      };

      IllustrationView.prototype.showIllustration = function() {
        return this.$('nav').html(this.pages.illustration);
      };

      return IllustrationView;

    })(Backbone.View);
    new IllustrationView;
    BrandingView = (function(_super) {
      __extends(BrandingView, _super);

      function BrandingView() {
        _ref1 = BrandingView.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      BrandingView.prototype.el = $('body');

      BrandingView.prototype.events = {
        'click #btn-branding': 'showBranding'
      };

      BrandingView.prototype.pages = {
        branding: _.template($('#branding').html())
      };

      BrandingView.prototype.showBranding = function() {
        return this.$('nav').html(this.pages.branding);
      };

      return BrandingView;

    })(Backbone.View);
    new BrandingView;
    EditorialView = (function(_super) {
      __extends(EditorialView, _super);

      function EditorialView() {
        _ref2 = EditorialView.__super__.constructor.apply(this, arguments);
        return _ref2;
      }

      EditorialView.prototype.el = $('body');

      EditorialView.prototype.events = {
        'click #btn-editorial': 'showEditorial'
      };

      EditorialView.prototype.pages = {
        editorial: _.template($('#editorial').html())
      };

      EditorialView.prototype.showEditorial = function() {
        return this.$('nav').html(this.pages.editorial);
      };

      return EditorialView;

    })(Backbone.View);
    new EditorialView;
    WebView = (function(_super) {
      __extends(WebView, _super);

      function WebView() {
        _ref3 = WebView.__super__.constructor.apply(this, arguments);
        return _ref3;
      }

      WebView.prototype.el = $('body');

      WebView.prototype.events = {
        'click #btn-web': 'showWeb'
      };

      WebView.prototype.pages = {
        web: _.template($('#web').html())
      };

      WebView.prototype.showWeb = function() {
        return this.$('nav').html(this.pages.web);
      };

      return WebView;

    })(Backbone.View);
    new WebView;
    FontView = (function(_super) {
      __extends(FontView, _super);

      function FontView() {
        _ref4 = FontView.__super__.constructor.apply(this, arguments);
        return _ref4;
      }

      FontView.prototype.el = $('body');

      FontView.prototype.events = {
        'click #btn-font': 'showFont'
      };

      FontView.prototype.pages = {
        font: _.template($('#font').html())
      };

      FontView.prototype.showFont = function() {
        return this.$('nav').html(this.pages.font);
      };

      return FontView;

    })(Backbone.View);
    new FontView;
    ServiceView = (function(_super) {
      __extends(ServiceView, _super);

      function ServiceView() {
        _ref5 = ServiceView.__super__.constructor.apply(this, arguments);
        return _ref5;
      }

      ServiceView.prototype.el = $('body');

      ServiceView.prototype.events = {
        'click #btn-service': 'showService'
      };

      ServiceView.prototype.pages = {
        service: _.template($('#service').html())
      };

      ServiceView.prototype.showService = function() {
        return this.$('nav').html(this.pages.service);
      };

      return ServiceView;

    })(Backbone.View);
    new ServiceView;
    VideoView = (function(_super) {
      __extends(VideoView, _super);

      function VideoView() {
        _ref6 = VideoView.__super__.constructor.apply(this, arguments);
        return _ref6;
      }

      VideoView.prototype.el = $('body');

      VideoView.prototype.events = {
        'click #btn-video': 'showVideo'
      };

      VideoView.prototype.pages = {
        video: _.template($('#video').html())
      };

      VideoView.prototype.showVideo = function() {
        return this.$('nav').html(this.pages.video);
      };

      return VideoView;

    })(Backbone.View);
    new VideoView;
    AboutView = (function(_super) {
      __extends(AboutView, _super);

      function AboutView() {
        _ref7 = AboutView.__super__.constructor.apply(this, arguments);
        return _ref7;
      }

      AboutView.prototype.el = $('body');

      AboutView.prototype.events = {
        'click #btn-about': 'showAbout'
      };

      AboutView.prototype.pages = {
        about: _.template($('#about').html())
      };

      AboutView.prototype.showAbout = function() {
        return this.$('nav').html(this.pages.about);
      };

      return AboutView;

    })(Backbone.View);
    return new AboutView;
  });

}).call(this);
