// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jQuery(function() {
    var AboutView, BodyView, BrandingView, EditorialView, FontView, IllustrationView, LogoView, ServiceView, VideoView, WebView, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
    LogoView = (function(_super) {
      __extends(LogoView, _super);

      function LogoView() {
        _ref = LogoView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      LogoView.prototype.tagName = 'div';

      LogoView.prototype.template = _.template($('#logo').html());

      LogoView.prototype.render = function() {
        this.$el.html(this.template);
        return this;
      };

      return LogoView;

    })(Backbone.View);
    IllustrationView = (function(_super) {
      __extends(IllustrationView, _super);

      function IllustrationView() {
        _ref1 = IllustrationView.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      IllustrationView.prototype.tagName = 'p';

      IllustrationView.prototype.template = _.template($('#illustration').html());

      IllustrationView.prototype.render = function() {
        this.$el.html(this.template);
        return this;
      };

      return IllustrationView;

    })(Backbone.View);
    BrandingView = (function(_super) {
      __extends(BrandingView, _super);

      function BrandingView() {
        _ref2 = BrandingView.__super__.constructor.apply(this, arguments);
        return _ref2;
      }

      BrandingView.prototype.tagName = 'p';

      BrandingView.prototype.template = _.template($('#branding').html());

      BrandingView.prototype.render = function() {
        this.$el.html(this.template);
        return this;
      };

      return BrandingView;

    })(Backbone.View);
    EditorialView = (function(_super) {
      __extends(EditorialView, _super);

      function EditorialView() {
        _ref3 = EditorialView.__super__.constructor.apply(this, arguments);
        return _ref3;
      }

      EditorialView.prototype.tagName = 'p';

      EditorialView.prototype.template = _.template($('#editorial').html());

      EditorialView.prototype.render = function() {
        this.$el.html(this.template);
        return this;
      };

      return EditorialView;

    })(Backbone.View);
    WebView = (function(_super) {
      __extends(WebView, _super);

      function WebView() {
        _ref4 = WebView.__super__.constructor.apply(this, arguments);
        return _ref4;
      }

      WebView.prototype.tagName = 'p';

      WebView.prototype.template = _.template($('#web').html());

      WebView.prototype.render = function() {
        this.$el.html(this.template);
        return this;
      };

      return WebView;

    })(Backbone.View);
    FontView = (function(_super) {
      __extends(FontView, _super);

      function FontView() {
        _ref5 = FontView.__super__.constructor.apply(this, arguments);
        return _ref5;
      }

      FontView.prototype.tagName = 'p';

      FontView.prototype.template = _.template($('#font').html());

      FontView.prototype.render = function() {
        this.$el.html(this.template);
        return this;
      };

      return FontView;

    })(Backbone.View);
    ServiceView = (function(_super) {
      __extends(ServiceView, _super);

      function ServiceView() {
        _ref6 = ServiceView.__super__.constructor.apply(this, arguments);
        return _ref6;
      }

      ServiceView.prototype.tagName = 'p';

      ServiceView.prototype.template = _.template($('#service').html());

      ServiceView.prototype.render = function() {
        this.$el.html(this.template);
        return this;
      };

      return ServiceView;

    })(Backbone.View);
    VideoView = (function(_super) {
      __extends(VideoView, _super);

      function VideoView() {
        _ref7 = VideoView.__super__.constructor.apply(this, arguments);
        return _ref7;
      }

      VideoView.prototype.tagName = 'p';

      VideoView.prototype.template = _.template($('#video').html());

      VideoView.prototype.render = function() {
        this.$el.html(this.template);
        return this;
      };

      return VideoView;

    })(Backbone.View);
    AboutView = (function(_super) {
      __extends(AboutView, _super);

      function AboutView() {
        _ref8 = AboutView.__super__.constructor.apply(this, arguments);
        return _ref8;
      }

      AboutView.prototype.tagName = 'p';

      AboutView.prototype.template = _.template($('#about').html());

      AboutView.prototype.render = function() {
        this.$el.html(this.template);
        return this;
      };

      return AboutView;

    })(Backbone.View);
    BodyView = (function(_super) {
      __extends(BodyView, _super);

      function BodyView() {
        _ref9 = BodyView.__super__.constructor.apply(this, arguments);
        return _ref9;
      }

      BodyView.prototype.el = $('body');

      BodyView.prototype.events = {
        'click #btn-logo': 'showLogo',
        'click #btn-illustration': 'showIllustration',
        'click #btn-branding': 'showBranding',
        'click #btn-editorial': 'showEditorial',
        'click #btn-web': 'showWeb',
        'click #btn-font': 'showFont',
        'click #btn-service': 'showService',
        'click #btn-video': 'showVideo',
        'click #btn-about': 'showAbout'
      };

      BodyView.prototype.initialize = function() {
        return this.showLogo();
      };

      BodyView.prototype.showLogo = function() {
        var logoView;
        logoView = new LogoView;
        return this.$('nav').html(logoView.render().el);
      };

      BodyView.prototype.showIllustration = function() {
        var illustrationView;
        illustrationView = new IllustrationView;
        return this.$('nav').html(illustrationView.render().el);
      };

      BodyView.prototype.showBranding = function() {
        var brandingView;
        brandingView = new BrandingView;
        return this.$('nav').html(brandingView.render().el);
      };

      BodyView.prototype.showEditorial = function() {
        var editorialView;
        editorialView = new EditorialView;
        return this.$('nav').html(editorialView.render().el);
      };

      BodyView.prototype.showWeb = function() {
        var webView;
        webView = new WebView;
        return this.$('nav').html(webView.render().el);
      };

      BodyView.prototype.showFont = function() {
        var fontView;
        fontView = new FontView;
        return this.$('nav').html(fontView.render().el);
      };

      BodyView.prototype.showService = function() {
        var serviceView;
        serviceView = new ServiceView;
        return this.$('nav').html(serviceView.render().el);
      };

      BodyView.prototype.showVideo = function() {
        var videoView;
        videoView = new VideoView;
        return this.$('nav').html(videoView.render().el);
      };

      BodyView.prototype.showAbout = function() {
        var aboutView;
        aboutView = new AboutView;
        return this.$('nav').html(aboutView.render().el);
      };

      return BodyView;

    })(Backbone.View);
    return new BodyView;
  });

}).call(this);
